### ISSUE TITLE
Credentials icon is too big on the side pane (wrong class ?)

### ISSUE THREAD

**Issue by jonesbusy** [jenkinsci/material-theme-plugin#12] opened 2022-03-11 05:06 UTC
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.332.1
OS: Linux - 5.14.14-200.fc34.x86_64
---
ace-editor:1.1
allure-jenkins-plugin:2.30.2
analysis-model-api:10.9.3
ansible:1.1
ansicolor:1.0.1
ant:1.13
antisamy-markup-formatter:2.7
apache-httpcomponents-client-4-api:4.5.13-1.0
artifactory:3.15.4
atlassian-bitbucket-server-integration:3.1.0
authentication-tokens:1.4
authorize-project:1.4.0
basic-branch-build-strategies:1.3.2
bitbucket-kubernetes-credentials:0.0.4
blueocean:1.25.3
blueocean-autofavorite:1.2.5
blueocean-bitbucket-pipeline:1.25.3
blueocean-commons:1.25.3
blueocean-config:1.25.3
blueocean-core-js:1.25.3
blueocean-dashboard:1.25.3
blueocean-display-url:2.4.1
blueocean-events:1.25.3
blueocean-git-pipeline:1.25.3
blueocean-github-pipeline:1.25.3
blueocean-i18n:1.25.3
blueocean-jwt:1.25.3
blueocean-personalization:1.25.3
blueocean-pipeline-api-impl:1.25.3
blueocean-pipeline-editor:1.25.3
blueocean-pipeline-scm-api:1.25.3
blueocean-rest:1.25.3
blueocean-rest-impl:1.25.3
blueocean-web:1.25.3
bootstrap4-api:4.6.0-3
bootstrap5-api:5.1.3-6
bouncycastle-api:2.25
branch-api:2.7.0
build-discarder:60.v1747b0eb632a
build-name-setter:2.2.0
build-user-vars-plugin:1.8
build-with-parameters:1.6
built-on-column:1.1
caffeine-api:2.9.2-29.v717aac953ff3
checks-api:1.7.2
cloudbees-bitbucket-branch-source:757.vddedc5f2589a_
cloudbees-disk-usage-simple:0.10
cloudbees-folder:6.708.ve61636eb_65a_5
code-coverage-api:2.0.4
command-launcher:1.6
conditional-buildstep:1.4.1
config-file-provider:3.9.0
configuration-as-code:1414.v878271fc496f
credentials:1074.v60e6c29b_b_44b_
credentials-binding:1.27.1
custom-tools-plugin:0.8
data-tables-api:1.11.4-3
display-url-api:2.3.5
docker-commons:1.19
docker-workflow:1.28
dtkit-api:3.0.0
durable-task:493.v195aefbb0ff2
echarts-api:5.3.0-2
email-ext:2.87
envinject:2.839.v52c702c10635
envinject-api:1.180.v98d833b_27470
extended-choice-parameter:346.vd87693c5a_86c
extended-read-permission:3.2
external-monitor-job:191.v363d0d1efdf8
favorite:2.4.0
file-operations:1.11
font-awesome-api:6.0.0-1
forensics-api:1.9.0
git:4.10.3
git-client:3.11.0
git-forensics:1.5.0
git-parameter:0.9.15
git-server:1.10
github:1.34.3
github-api:1.301-378.v9807bd746da5
github-branch-source:1583.v18d333ef7379
gitlab-api:1.0.6
gitlab-branch-source:1.5.9
gradle:1.38
h2-api:1.4.199
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-1.0
hidden-parameter:0.0.4
htmlpublisher:1.29
http_request:1.14
inline-pipeline:1.0.1
ivy:2.1
jackson2-api:2.13.1-246.va8a9f3eaf46a
jacoco:3.3.1
javadoc:217.v905b_86277a_2a_
javax-activation-api:1.2.0-2
javax-mail-api:1.6.2-5
jaxb:2.3.0.1
jdk-tool:1.5
jenkins-design-language:1.25.3
jenkins-multijob-plugin:1.36
jira:3.7
jjwt-api:0.11.2-9.c8b45b8bb173
jnr-posix-api:3.1.7-2
job-dsl:1.78.3
jquery:1.12.4-1
jquery-detached:1.2.1
jquery3-api:3.6.0-2
jsch:0.1.55.2
junit:1.56
kubernetes:3546.v6103d89542d6
kubernetes-client-api:5.11.2-182.v0f1cf4c5904e
kubernetes-credentials:0.9.0
kubernetes-credentials-provider:0.20
ldap:2.8
locale:144.v1a_998824ddb_3
lockable-resources:2.14
login-theme:1.1
mailer:408.vd726a_1130320
mapdb-api:1.0.9.0
mask-passwords:3.0
material-theme:0.4.1
matrix-auth:3.1
matrix-project:758.v7a_ea_491852f3
maven-plugin:3.18
metrics:4.1.6.1
momentjs:1.1.1
nested-view:1.24
next-build-number:1.8
next-executions:1.0.15
nodejs:1.5.1
okhttp-api:4.9.3-105.vb96869f8ac3a
openshift-client:1.0.37
openshift-k8s-credentials:17.va_c9387db_a_a_65
openshift-login:1.0.27
openshift-sync:1.0.53
pam-auth:1.7
parameter-separator:1.3
parameterized-trigger:2.43
pipeline-build-step:2.16
pipeline-github-lib:36.v4c01db_ca_ed16
pipeline-graph-analysis:188.v3a01e7973f2c
pipeline-input-step:446.vf27b_0b_83500e
pipeline-maven:3.10.0
pipeline-milestone-step:100.v60a_03cd446e1
pipeline-model-api:2.2064.v5eef7d0982b_e
pipeline-model-definition:2.2064.v5eef7d0982b_e
pipeline-model-extensions:2.2064.v5eef7d0982b_e
pipeline-npm:0.9.2
pipeline-rest-api:2.23
pipeline-stage-step:291.vf0a8a7aeeb50
pipeline-stage-tags-metadata:2.2064.v5eef7d0982b_e
pipeline-stage-view:2.23
pipeline-utility-steps:2.12.0
plain-credentials:1.8
plugin-util-api:2.14.0
popper-api:1.16.1-2
popper2-api:2.11.2-1
prism-api:1.26.0-2
prometheus:2.0.11
pubsub-light:1.16
purge-build-queue-plugin:24.v3e0e709b_f62e
resource-disposer:0.17
run-condition:1.5
scm-api:595.vd5a_df5eb_0e39
scm-filter-branch-pr:0.5.1
script-security:1140.vf967fb_efa_55a_
sidebar-link:2.1.0
simple-theme-plugin:103.va_161d09c38c7
skip-notifications-trait:1.0.5
snakeyaml-api:1.29.1
sonar:2.14
sse-gateway:1.25
ssh-agent:1.24.1
ssh-credentials:1.19
ssh-slaves:1.806.v2253cedd3295
sshd:3.1.0
strict-crumb-issuer:2.1.0
structs:308.v852b473a2b8c
subversion:2.15.2
theme-manager:0.6
timestamper:1.17
token-macro:280.v97a_82642793c
trilead-api:1.0.13
uno-choice:2.6.0
variant:1.4
warnings-ng:9.11.1
windows-slaves:1.8
workflow-aggregator:2.7
workflow-api:1138.v619fd5201b_2f
workflow-basic-steps:941.vdfe1b_a_132c64
workflow-cps:2660.vb_c0412dc4e6d
workflow-cps-global-lib:564.ve62a_4eb_b_e039
workflow-durable-task-step:1121.va_65b_d2701486
workflow-job:1174.vdcb_d054cf74a_
workflow-multibranch:711.vdfef37cda_816
workflow-remote-loader:1.5
workflow-scm-step:2.13
workflow-step-api:622.vb_8e7c15b_c95a_
workflow-support:815.vd60466279fc8
ws-cleanup:0.40
xunit:3.0.5
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

docker / helm chart

### Reproduction steps

I think the credentials menu appear on the left with the permission Credentials/View

### Expected Results

Icon of normal size (medium ?)

If I fix the class to 'md' icon display a bit better (but a bit too big)

![credential_size_fixed](https://user-images.githubusercontent.com/825750/157805513-1b2c9aa4-154f-48bf-b93f-dd0a38a972be.PNG)

### Actual Results

Icon of large size

![credentials](https://user-images.githubusercontent.com/825750/157805274-47141385-4222-49af-add1-1e59b391c674.PNG)

### Anything else?

Thanks you!

**Comment by timbrown5** [comment] 2022-03-14 17:10
I think the issue is that the plugin specifies the wrong class when it adds the image to the sidebar (the others are `icon-md` and it is `icon-xlg`).
If `icon-xlg` is not used anywhere else I cloud make it a synonym for `icon-md`.

**Comment by jonesbusy** [comment] 2022-03-15 06:15
CF 

https://issues.jenkins.io/browse/JENKINS-33191

I thought it would be fixed in 2016 but seems not. Unless there is a regression with https://github.com/jenkinsci/credentials-plugin/pull/248

**Comment by timja** [comment] 2022-03-19 11:22
Might be fixed by https://github.com/jenkinsci/credentials-plugin/pull/287

**Comment by timbrown5** [comment] 2022-08-31 14:55
#41 - Core has updated the icon, so I will remove the override (no longer needed).

**Comment by timbrown5** [comment] 2022-09-12 07:53
Should be fioxed in 0.5.0-rc83.6557e02980de

**Closed as completed by timbrown5** 2022-09-12 07:53 UTC
Labels: bug
